version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: 0.0.0.0
      MYSQL_DATABASE: "teatro"
      MYSQL_ROOT_PASSWORD: "Rut123."
    volumes:
      - /.docker/db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "laravelapp"
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: bash -c 'composer install && php artisan migrate && php artisan key:generate  &&  php artisan db:seed'

  app2:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "laravelapp"
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
